### ISSUE TITLE
metall manager capacity limit SEGFAULT

### ISSUE THREAD

**Issue by liss-h** [LLNL/metall#328] opened 2024-09-02 14:00 UTC
The following code causes a segfault:

```c++
std::string const path{std::format("/tmp/metall-test-capacity-{}", std::random_device{}())};

metall::manager manager{metall::create_only, path, 1};
std::vector<uint64_t, metall::manager::allocator_type<uint64_t>> vec{manager.get_allocator<uint64_t>()};

for (size_t cap = 0; cap < 100'000'000; cap += 1'000'000) {
    vec.resize(cap);
}
```

Whereas it throws `bad_alloc` (as expected) if you immediately `.resize()` to 100'000'000.

**Comment by KIwabuchi** [comment] 2024-09-10 02:43
Thanks for reporting the issue. I'll investigate why bad_alloc is not thrown.

**Comment by KIwabuchi** [comment] 2024-09-19 21:35
Unfortunately, I cannot reproduce the issue on my side. I also checked Metall code but couldn't find an issue.
I'll keep investigating and let you know once I find something.

**Comment by liss-h** [comment] 2024-10-01 11:40
You are on MacOS, right? Maybe there is some difference between MacOS and Linux that prevents you from being able to reproduce it. 

Could you try increasing the maximum `cap` value?

**Comment by KIwabuchi** [comment] 2024-10-04 20:19
I also tried it on Linux. I keep investigating the issue.

**Comment by KIwabuchi** [comment] 2024-10-05 05:34
I think I was able to fix the issue: https://github.com/LLNL/metall/pull/334.
It has been merged into the develop branch.

**Comment by liss-h** [comment] 2024-10-08 12:53
Thanks, that PR seems to have resolved the issue. You can close this if you want

**Closed** 2024-10-10 22:19 UTC
